# Generated by Django 4.1.5 on 2023-01-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0002_yahiko'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahiko',
            name='age',
            field=models.IntegerField(default=21),
        ),
    ]
