# Generated by Django 4.1.5 on 2023-01-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0003_yahiko_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yahiko',
            name='age',
        ),
    ]
