# Generated by Django 4.1.5 on 2023-01-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0005_place_akatsukiteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akatsukiteam',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='akatsukiteam',
            old_name='team',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='akatsukiteam',
            name='email',
            field=models.CharField(default='coolbro@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='akatsukiteam',
            name='purpose',
            field=models.CharField(default='peace', max_length=30),
        ),
    ]
