# Generated by Django 4.1.5 on 2023-01-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peace', '0006_rename_name_akatsukiteam_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akatsukiteam',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='akatsukiteam',
            old_name='lastname',
            new_name='lname',
        ),
    ]
